
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"E:\resetpw\build\pw_rst_assets\page_2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)



def show_pw_reset_modal(parent=None):
    import tkinter as tk
    if parent is None:
        parent = tk.Tk()
        parent.withdraw()
    modal = tk.Toplevel(parent)
    modal.title("Password Reset")
    modal.geometry("1000x700")
    modal.configure(bg = "#000000")
    modal.transient(parent)
    modal.grab_set()
    modal.focus_set()
    modal.resizable(False, False)

    canvas = Canvas(
        modal,
        bg = "#000000",
        height = 700,
        width = 1000,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )
    canvas.place(x = 0, y = 0)
    button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"), master=modal)
    button_1 = Button(
        modal,
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        bg= "#000000",
        activebackground= "#000000",
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.image = button_image_1
    button_1.place(x=250.0, y=496.0, width=500.0, height=60.0)

    canvas.create_text(200.0, 321.0, anchor="nw", text="Confirm Password:", fill="#FFFFFF", font=("Inter Medium", 24 * -1))

    entry_image_1 = PhotoImage(file=relative_to_assets("entry_1.png"), master=modal)
    entry_bg_1 = canvas.create_image(500.0, 240.0, image=entry_image_1)
    entry_1 = Entry(modal, bd=0, bg="#D9D9D9", fg="#000716", highlightthickness=0)
    entry_1.place(x=210.0, y=210.0, width=580.0, height=58.0)

    entry_image_2 = PhotoImage(file=relative_to_assets("entry_2.png"), master=modal)
    entry_bg_2 = canvas.create_image(500.0, 393.0, image=entry_image_2)
    entry_2 = Entry(modal, bd=0, bg="#D9D9D9", fg="#000716", highlightthickness=0)
    entry_2.place(x=210.0, y=363.0, width=580.0, height=58.0)

    canvas.create_text(200.0, 175.0, anchor="nw", text="New Password:", fill="#FFFFFF", font=("Inter Medium", 24 * -1))
    canvas.create_text(349.0, 89.0, anchor="nw", text="PASSWORD RESET", fill="#800000", font=("Inter ExtraBold", 32 * -1))

    button_image_2 = PhotoImage(file=relative_to_assets("button_2.png"), master=modal)
    button_2 = Button(
        modal,
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        bg="#000000",   
        activebackground="#000000",
        command=modal.destroy,
        relief="flat"
    )
    button_2.image = button_image_2
    button_2.place(x=949.0, y=8.0, width=40.0, height=40.0)

    # Wait for modal to close before returning
    modal.wait_window()

# If run directly, show as standalone for testing
if __name__ == "__main__":
    show_pw_reset_modal()
