
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent.parent.parent.parent.parent.parent 
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\adm_sett_2fa_setup_assets\step_5")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1400x841")
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 841,
    width = 1400,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    748.0,
    1400.0,
    841.0,
    fill="#800000",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    700.0,
    473.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#000000",
    fg="#FFFFFF",
    insertbackground="#FFFFFF",
    font=("Inter Light", 30),
    highlightthickness=0
)
entry_1.place(
    x=365.0,
    y=435.0,
    width=670.0,
    height=70.0
)

canvas.create_text(
    325.0,
    354.0,
    anchor="nw",
    text="Your 2FA key:",
    fill="#FFFFFF",
    font=("Inter Light", 36 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    700.0,
    238.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    bg="#000000",
    activebackground="#000000",
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=602.0,
    y=583.0,
    width=195.4391326904297,
    height=73.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    bg="#800000",
    activebackground="#800000",
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=471.0,
    y=774.0,
    width=457.0,
    height=41.0
)
window.resizable(False, False)
window.mainloop()
