
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent.parent.parent.parent.parent.parent 
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\adm_sett_2fa_setup_assets\step_1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1400x841")
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 841,
    width = 1400,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    748.0,
    1400.0,
    841.0,
    fill="#800000",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    699.5,
    468.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#000000",
    fg="#FFFFFF",
    font=("Inter Light", 30, "normal"),
    insertbackground="#FFFFFF",
    highlightthickness=0
)
entry_1.place(
    x=311.5,
    y=418.5,
    width=776.0,
    height=100.0
)

canvas.create_text(
    254.0,
    331.0,
    anchor="nw",
    text="Username:",
    fill="#FFFFFF",
    font=("Inter Light", 36 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    700.0,
    213.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    bg="#000000",
    activebackground="#000000",
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=277.0,
    y=617.0,
    width=220.17446899414062,
    height=65.53191375732422
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    bg="#000000",
    activebackground="#000000",
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=900.0,
    y=617.0,
    width=222.48085021972656,
    height=65.6907958984375
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    bg="#800000",
    activebackground="#800000",
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=471.0,
    y=774.0,
    width=457.0,
    height=41.0
)
window.resizable(False, False)
window.mainloop()
