
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent.parent.parent.parent.parent.parent 
ASSETS_PATH = OUTPUT_PATH / Path(r"assets\adm_sett_2fa_setup_assets\step_2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1400x841")
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 841,
    width = 1400,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    748.0,
    1400.0,
    841.0,
    fill="#800000",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    699.0,
    175.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    bg="#000000",
    activebackground="#000000",
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=592.6397705078125,
    y=671.54931640625,
    width=232.5906982421875,
    height=63.383365631103516
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    703.3471069335938,
    449.0,
    image=image_image_2
)

canvas.create_text(
    535.0,
    611.838623046875,
    anchor="nw",
    text="2fa code Goes here",
    fill="#FFFFFF",
    font=("Inter ExtraLight", 32 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    bg="#800000",
    activebackground="#800000",
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=471.0,
    y=774.0,
    width=457.0,
    height=41.0
)
window.resizable(False, False)
window.mainloop()
