# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


def relative_to_assets(path: str) -> Path:
    ASSETS_PATH = Path(__file__).parent.parent.parent.parent.parent / "assets" / "ani_assets"
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("720x720")
window.configure(bg = "#000000")


canvas = Canvas(
    window,
    bg = "#000000",
    height = 721,
    width = 720,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    1.0,
    721.0,
    73.0,
    fill="#800000",
    outline="")

canvas.create_rectangle(
    2.0,
    649.0,
    723.0,
    721.0,
    fill="#800000",
    outline="")

canvas.create_rectangle(
    0.0,
    19.0,
    87.0,
    47.0,
    fill="#834343",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat",
    activebackground="#834343"  # Match background color
)
button_1.place(
    x=9.0,
    y=24.0,
    width=18.0,
    height=18.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat",
    activebackground="#834343"  # Match background color
)
button_2.place(
    x=35.0,
    y=24.0,
    width=18.0,
    height=18.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat",
    activebackground="#834343"  # Match background color
)
button_3.place(
    x=61.0,
    y=24.0,
    width=18.0,
    height=18.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat",
    activebackground="#000000"  # Match background color
)
button_4.place(
    x=539.0,
    y=666.0,
    width=27.0,
    height=26.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat",
    activebackground="#000000"  # Match background color
)
button_5.place(
    x=583.0,
    y=666.0,
    width=26.0,
    height=26.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat",
    activebackground="#000000"  # Match background color
)
button_6.place(
    x=622.0,
    y=666.0,
    width=27.0,
    height=26.0
)

canvas.create_text(
    536.0,
    692.0,
    anchor="nw",
    text="Cancel",
    fill="#FFFFFF",
    font=("Inter Light", 10 * -1)
)

canvas.create_text(
    579.0,
    692.0,
    anchor="nw",
    text="Draft",
    fill="#FFFFFF",
    font=("Inter Light", 10 * -1)
)

canvas.create_text(
    619.0,
    692.0,
    anchor="nw",
    text="Save",
    fill="#FFFFFF",
    font=("Inter Light", 10 * -1)
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    bg="#800000",
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat",
    activebackground="#800000"  # Match maroon background color
)
button_7.place(
    x=73.0,
    y=672.0,
    width=125.0,
    height=26.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    360.5,
    222.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#000000",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=83.0,
    y=197.0,
    width=555.0,
    height=48.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    162.5,
    312.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#000000",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=83.0,
    y=287.0,
    width=159.0,
    height=48.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    360.5,
    312.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#000000",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=281.0,
    y=287.0,
    width=159.0,
    height=48.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    558.5,
    312.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#000000",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=479.0,
    y=287.0,
    width=159.0,
    height=48.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    558.5,
    401.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#000000",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=479.0,
    y=376.0,
    width=159.0,
    height=48.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    360.5,
    401.0,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#000000",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=281.0,
    y=376.0,
    width=159.0,
    height=48.0
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    162.5,
    401.0,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#000000",
    fg="#000716",
    highlightthickness=0
)
entry_7.place(
    x=83.0,
    y=376.0,
    width=159.0,
    height=48.0
)

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    162.5,
    490.0,
    image=entry_image_8
)
entry_8 = Entry(
    bd=0,
    bg="#000000",
    fg="#000716",
    highlightthickness=0
)
entry_8.place(
    x=83.0,
    y=465.0,
    width=159.0,
    height=48.0
)

entry_image_9 = PhotoImage(
    file=relative_to_assets("entry_9.png"))
entry_bg_9 = canvas.create_image(
    459.5,
    490.0,
    image=entry_image_9
)
entry_9 = Entry(
    bd=0,
    bg="#000000",
    fg="#000716",
    highlightthickness=0
)
entry_9.place(
    x=281.0,
    y=465.0,
    width=357.0,
    height=48.0
)

canvas.create_text(
    70.0,
    166.0,
    anchor="nw",
    text="Item Name:",
    fill="#FFFFFF",
    font=("Inter Medium", 18 * -1)
)

canvas.create_text(
    70.0,
    258.0,
    anchor="nw",
    text="Brand:",
    fill="#FFFFFF",
    font=("Inter Medium", 18 * -1)
)

canvas.create_text(
    73.0,
    345.0,
    anchor="nw",
    text="Unit of Measure:",
    fill="#FFFFFF",
    font=("Inter Medium", 18 * -1)
)

canvas.create_text(
    271.0,
    345.0,
    anchor="nw",
    text="In:",
    fill="#FFFFFF",
    font=("Inter Medium", 18 * -1)
)

canvas.create_text(
    469.0,
    349.0,
    anchor="nw",
    text="Minimum Stock:",
    fill="#FFFFFF",
    font=("Inter Medium", 18 * -1)
)

canvas.create_text(
    70.0,
    433.0,
    anchor="nw",
    text="Price Per Unit:",
    fill="#FFFFFF",
    font=("Inter Medium", 18 * -1)
)

canvas.create_text(
    271.0,
    433.0,
    anchor="nw",
    text="Supplier:",
    fill="#FFFFFF",
    font=("Inter Medium", 18 * -1)
)

canvas.create_text(
    271.0,
    258.0,
    anchor="nw",
    text="Type:",
    fill="#FFFFFF",
    font=("Inter Medium", 18 * -1)
)

canvas.create_text(
    469.0,
    258.0,
    anchor="nw",
    text="Location:",
    fill="#FFFFFF",
    font=("Inter Medium", 18 * -1)
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_8 clicked"),
    relief="flat",
    activebackground="#000000"  # Match background color
)
button_8.place(
    x=227.0,
    y=299.0,
    width=25.0,
    height=25.0
)

button_image_9 = PhotoImage(
    file=relative_to_assets("button_9.png"))
button_9 = Button(
    image=button_image_9,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_9 clicked"),
    relief="flat",
    activebackground="#000000"  # Match background color
)
button_9.place(
    x=425.0,
    y=299.0,
    width=25.0,
    height=25.0
)

button_image_10 = PhotoImage(
    file=relative_to_assets("button_10.png"))
button_10 = Button(
    image=button_image_10,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_10 clicked"),
    relief="flat",
    activebackground="#000000"  # Match background color
)
button_10.place(
    x=623.0,
    y=299.0,
    width=25.0,
    height=25.0
)

button_image_11 = PhotoImage(
    file=relative_to_assets("button_11.png"))
button_11 = Button(
    image=button_image_11,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_11 clicked"),
    relief="flat",
    activebackground="#000000"  # Match background color
)
button_11.place(
    x=227.0,
    y=388.0,
    width=25.0,
    height=25.0
)

button_image_12 = PhotoImage(
    file=relative_to_assets("button_12.png"))
button_12 = Button(
    image=button_image_12,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_12 clicked"),
    relief="flat",
    activebackground="#000000"  # Match background color
)
button_12.place(
    x=623.0,
    y=477.0,
    width=25.0,
    height=25.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    360.0,
    37.0,
    image=image_image_1
)
window.resizable(False, False)
window.mainloop()
